nutui-uniapp/nutui-uniapp

- packages/nutui/components/configprovider/configprovider.vue
https://github.com/yang1206/uniapp-nutui/issues/13#issue-1854474940
> fix(configProvider): 取值错误问题

- docs/components/dentry/picker.md
- example/src/pages/demo/dentry/picker/index.vue
- packages/nutui/components/picker/picker.ts
- packages/nutui/components/picker/picker.vue
- packages/nutui/components/picker/use-picker.ts
- packages/nutui/components/pickercolumn/pickercolumn.ts
- packages/nutui/components/pickercolumn/pickercolumn.vue
- packages/nutui/components/pickercolumn/types.ts
support custom column field names
> feat: (picker) support custom column field names

- packages/nutui/components/actionsheet/actionsheet.vue
> fix: (actionsheet) 修复 close-abled 失效问题

- packages/nutui/components/card/card.vue
> feat: (card) 不填写价格则不展示

- packages/nutui/components/card/card.vue
- packages/nutui/components/categorypane/categorypane.vue
- packages/nutui/components/comment/components/CmtHeader.vue
- packages/nutui/components/comment/components/CmtImages.vue
- packages/nutui/components/dollmachine/dollmachine.vue
- packages/nutui/components/empty/empty.vue
- packages/nutui/components/fixednav/fixednav.vue
- packages/nutui/components/hiteggs/hiteggs.vue
- packages/nutui/components/marquee/marquee.vue
- packages/nutui/components/numberkeyboard/numberkeyboard.vue
- packages/nutui/components/sku/components/SkuHeader.vue
- packages/nutui/components/skuheader/skuheader.vue
- packages/nutui/components/turntable/turntable.vue
部分组件使用`<img>`标签，在微信小程序中是无法解析的，已经替换成`<image>`
> fix: 解决多个组件包含img导致微信小程序不通过bug

- packages/nutui/components/inputnumber/inputnumber.vue
bug[视频地址](https://imgur.com/R5h7Q1G)
> fix: :bug: 修改inputnumber组件失去焦点以及change的时候展示值丢失问题

- docs/components/business/addresslist.md
- packages/nutui/components/addresslist/addresslist.ts
- packages/nutui/components/addresslist/addresslist.vue
1. 修改地址列表组件文档
2. 新增地址列表组件回调index索引值
> feat: :sparkles: 地址列表组件新增index索引回调

- docs/components/dentry/input.md
- packages/nutui/components/input/input.ts
- packages/nutui/components/input/input.vue
新增input自定义属性，感觉没有这个二开起来太麻烦了 o(╥﹏╥)o
> feat: (input) 新增Input组件customStyle自定义属性

- packages/nutui/components/tabs/tabs.vue
> fix: (cascader) 动态加载标题无法正确显示

- docs/components/dentry/searchbar.md
- packages/nutui/components/searchbar/searchbar.ts
- packages/nutui/components/searchbar/searchbar.vue
> feat: (searchbar) 增加cursor-spacing属性

- packages/nutui/components/radio/index.scss
- packages/nutui/components/radio/radio.vue
- packages/nutui/components/radiogroup/radiogroup.vue
> fix: (radio) 修复radio-group的textPosition属性没有响应式

- packages/nutui/components/radio/index.scss
> fix: (radio) 修复按钮类型激活背景边框样式

- example/src/pages/demo/dentry/textarea/index.vue
- packages/nutui/components/textarea/textarea.vue
> fix: (textarea) 修复readonly 属性失效与无法渲染换行

- docs/components/exhibition/imagepreview.md
- packages/nutui/components/imagepreview/imagepreview.ts
- packages/nutui/components/imagepreview/imagepreview.vue
- packages/nutui/components/imagepreview/index.scss
> feat: (imagepreview) 支持双指缩放图片

- packages/nutui/components/searchbar/searchbar.vue
> fix: (searchbar) autofocus无效

- docs/components/dentry/input.md
- packages/nutui/components/input/input.ts
- packages/nutui/components/input/input.vue
> feat(input): 新增 placeholder-style 和 placeholder-class 属性

- docs/components/dentry/input.md
- docs/components/dentry/textarea.md
- packages/nutui/components/input/input.ts
- packages/nutui/components/input/input.vue
- packages/nutui/components/textarea/textarea.ts
- packages/nutui/components/textarea/textarea.vue
- packages/nutui/components/textarea/type.ts
> feat：补充input、textarea部分属性

- eslint.config.js
- example/tsconfig.json
- packages/nutui/components/navbar/index.scss
- packages/nutui/components/navbar/navbar.ts
- packages/nutui/components/navbar/navbar.vue
> feat(navbar): 适配小程序状态栏高度,优化代码

- example/src/pages/demo/nav/menu/index.vue
- packages/nutui/components/menuitem/menuitem.vue
> fix(menu): 修复自定义选中颜色失效

- docs/components/exhibition/noticebar.md
- example/src/pages/demo/exhibition/noticebar/index.vue
- packages/nutui/components/noticebar/noticebar.ts
- packages/nutui/components/noticebar/noticebar.vue
> feat(noticebar): 新增`field-name`属性,支持传入数组对象

- packages/nutui/components/_utils/style.ts
> fix: 修复支付宝小程序编译错误

- packages/nutui/components/elevator/elevator.vue
- packages/nutui/components/elevator/index.scss
> fix(elevator): 修复滚动后无法点击问题

- docs/components/dentry/input.md
- packages/nutui/components/input/input.ts
- packages/nutui/components/input/input.vue
> feat(input): modelValue的类型支持number

- docs/components/dentry/form.md
- example/src/pages/demo/dentry/form/index.vue
- packages/nutui/components/formitem/formitem.vue
> feat(form): formItem的required的星号支持从rules中自动判断是否显示

- docs/components/dentry/cascader.md
- example/src/pages/demo/dentry/cascader/index.vue
- packages/nutui/components/cascader/cascader.vue
> feat(cascader): 新增title插槽

- packages/nutui/components/inputnumber/inputnumber.vue
> fix(inputnumber): 修复步进按钮禁用功能无效

- example/src/pages/demo/exhibition/avatar/index.vue
- packages/nutui/components/avatar/avatar.vue
- packages/nutui/components/avatargroup/avatargroup.ts
- packages/nutui/components/avatargroup/avatargroup.vue
> fix(avatar): 修复maxCount属性无效

- packages/nutui/components/_utils/is.ts
`isPromise` 判断错误，`is(val, 'Promise')` 与 `isObject(val)` 不可能同时为 `true`。
> fix(utils): isPromise 判断错误

- docs/components/dentry/form.md
- example/src/pages/demo/dentry/form/index.vue
- packages/nutui/components/form/form.ts
- packages/nutui/components/form/types.ts
- packages/nutui/components/formitem/formitem.ts
- packages/nutui/components/formitem/formitem.vue
- packages/nutui/components/formitem/index.scss
- packages/nutui/components/formitem/types.ts
> feat(form): 支持配置表单布局

- example/src/App.vue
- example/src/pages/demo/basic/popup/index.vue
- example/src/store/modules/app/index.ts
- packages/nutui/components/overlay/overlay.ts
- packages/nutui/components/overlay/overlay.vue
- packages/nutui/components/popup/popup.vue
- packages/nutui/components/popup/use-popup.ts
- packages/nutui/components/transition/transition.ts
- packages/nutui/components/transition/transition.vue
- packages/nutui/components/transition/use-transition.ts
> fix(popup): 修复destroy-on-close无效 

- packages/nutui/components/menu/menu.vue
- packages/nutui/components/menuitem/index.scss
- packages/nutui/components/menuitem/menuitem.vue
> fix(menu): 修复menu闪屏动画错误以及位置偏移

- docs/components/nav/navbar.md
- example/src/pages/demo/nav/navbar/index.vue
- packages/nutui/components/navbar/index.scss
> fix(navbar): 修复标题居中等样式问题

- packages/nutui/components/sku/sku.vue
> fix(sku): 修复小程序下选项内容的滚动问题

- .stylelintrc
- example/src/pages/demo/nav/tabs/index.vue
- packages/nutui/components/tabs/index.scss
- packages/nutui/components/tabs/tabs.vue
> fix(tabs): 修复嵌套使用时的样式错乱问题

- docs/components/dentry/radio.md
- example/src/pages/demo/dentry/radio/index.vue
- packages/nutui/components/radio/index.scss
- packages/nutui/components/radio/radio.ts
- packages/nutui/components/radio/radio.vue
> feat(radio): 组件设置 button 形状时支持改变大小

- docs/components/exhibition/watermark.md
- example/src/pages/demo/exhibition/watermark/index.vue
- packages/nutui/components/watermark/watermark.ts
- packages/nutui/components/watermark/watermark.vue
> feat(watermark): 支持多行文字水印

- packages/nutui/components/input/input.vue
> perf(input): 使用computed代替函数调用

- packages/nutui/components/card/card.vue
> feat(card): 商品卡片组件增加shopName插槽，用于店铺名称自定义

- packages/nutui/components/categorypane/categorypane.vue
> fix(categorypane): 商品分类面板组件默认插槽不生效

- docs/components/basic/button.md
- packages/nutui/components/button/button.ts
- packages/nutui/components/button/button.vue
- packages/nutui/components/button/index.scss
`button` 支持 `hover-class` 相关配置
> feat(button): 新增hover-class相关属性

- packages/nutui/components/navbar/navbar.vue
> fix(navbar): 修复zIndex无效问题

- packages/nutui/components/table/table.ts
- packages/nutui/components/table/types.ts
[data](https://www.uniapp-nutui.tech/components/exhibition/table.html#props) 属性定义与文档有出入
lint error [sorter](https://www.uniapp-nutui.tech/components/exhibition/table.html#tablecolumnprops) 排序用的是js sort 返回值是number
```ts
/**
* Sorts an array in place.
* This method mutates the array and returns a reference to the same array.
* @param compareFn Function used to determine the order of the elements. It is expected to return
* a negative value if the first argument is less than the second argument, zero if they're equal, and a positive
* value otherwise. If omitted, the elements are sorted in ascending, ASCII character order.
* ```ts
* [11,2,22,1].sort((a, b) => a - b)
* ```
*/
sort(compareFn?: (a: T, b: T) => number): this;
```
> table props 类型定义问题

- docs/components/dentry/input.md
- packages/nutui/components/input/input.ts
- packages/nutui/components/input/input.vue
> feat(input): 新增input事件

- packages/nutui/components/input/type.ts
> fix(input): 移除InputType重复类型

- docs/guide/faq.md
- docs/guide/quick-start.md
- docs/guide/theme.md
添加mergeVirtualHostAttributes说明
> docs: 添加mergeVirtualHostAttributes说明

- docs/components/bingo/marquee.md
- packages/nutui/components/marquee/marquee.ts
- packages/nutui/components/marquee/marquee.vue
> feat(marquee): 新增disabled属性

- docs/components/dentry/textarea.md
- packages/nutui/components/textarea/textarea.ts
- packages/nutui/components/textarea/textarea.vue
新增placeholder-style、placeholder-class属性
> feat(textarea): 新增placeholder-style、placeholder-class属性

- docs/guide/quick-start.md
- packages/nutui/components/navbar/index.scss
- packages/nutui/components/navbar/navbar.vue
- scripts/uni.ts
> fix(navbar): 修复在APP上顶部安全距离无效的问题

- packages/nutui/components/tabs/tabs.ts
> fix(tabs): align属性类型错误

- docs/components/basic/overlay.md
- docs/components/nav/navbar.md
- docs/components/nav/tabs.md
> docs: overlay、tabs默认z-index错误

- docs/components/basic/popup.md
- packages/nutui/components/transition/transition.vue
https://github.com/nutui-uniapp/nutui-uniapp/issues/192#issuecomment-1959398402
link #192, #191
Fix #191 . Fix #192 .
> fix(popup)!: destroy-on-close仅支持H5与微信小程序

- packages/nutui/components/menu/menu.vue
- packages/nutui/components/menuitem/index.scss
- packages/nutui/components/menuitem/menuitem.vue
> fix(menu): 偏移位置错误, app 端v-show 无效

- packages/nutui/components/elevator/elevator.vue
- packages/nutui/components/hiteggs/hiteggs.vue
- packages/nutui/components/input/input.vue
- packages/nutui/components/menuitem/index.scss
- packages/nutui/components/menuitem/menuitem.vue
- packages/nutui/components/noticebar/noticebar.vue
- packages/nutui/components/popover/popover.vue
- packages/nutui/components/searchbar/searchbar.vue
- packages/nutui/components/subsidenavbar/subsidenavbar.vue
- packages/nutui/components/switch/switch.vue
- packages/nutui/components/toast/toast.vue
- packages/nutui/components/toast/use-toast.ts
- packages/nutui/components/transition/index.scss
- packages/nutui/components/transition/use-transition.ts
- packages/nutui/styles/helpers.scss
- packages/nutui/styles/index.scss
为避免app端v-show兼容问题，使用 `nut-hidden` 替换 `v-show`
> refactor: nut-hidden替换v-show

- packages/nutui/components/form/form.vue
> fix(form): 修复prop类型为数组时required校验无效的问题

- packages/nutui/components/menuitem/menuitem.vue
- packages/nutui/components/popup/use-popup.ts
> fix(popup,menu): 修复 popup组件update:visible事件重复调用与menu 组件close 事件在小程序中无法触发

- docs/components/dentry/cascader.md
- example/src/pages/demo/dentry/cascader/index.vue
- packages/nutui/components/cascader/tree.ts
> 修复leaf等于false并且children为空时可以选择成功的问题

- docs/components/exhibition/avatar.md
- packages/nutui/components/avatar/avatar.ts
- packages/nutui/components/avatar/avatar.vue
- packages/nutui/components/avatar/index.scss
- packages/nutui/components/avatar/type.ts
- packages/nutui/components/avatargroup/avatargroup.ts
- packages/nutui/components/avatargroup/avatargroup.vue
- packages/nutui/components/avatargroup/index.scss
`nut-avatar` 修复size、shape无效以及无法正确从group继承
> fix(avatar): 修复size、shape无效以及无法正确从group继承

- packages/nutui/components/avatar/avatar.vue
`nut-avatar-group` 修复z-index无效
> fix(avatar-group): 修复z-index无效

- packages/nutui/components/textarea/index.ts
- packages/nutui/components/textarea/textarea.ts
- packages/nutui/components/textarea/textarea.vue
- packages/nutui/components/textarea/type.ts
> fix(textarea): 修复类型导出缺失

- packages/nutui/components/input/index.scss
- packages/nutui/components/input/input.vue
- packages/nutui/components/input/type.ts
> style(input): 规范代码格式

- packages/nutui/components/input/input.vue
- packages/nutui/components/textarea/index.scss
- packages/nutui/components/textarea/textarea.ts
- packages/nutui/components/textarea/textarea.vue
`nut-textarea` 代码格式对齐`nut-input`
> style(textarea): 代码格式对齐input

- docs/components/dentry/textarea.md
- packages/nutui/components/textarea/textarea.ts
- packages/nutui/components/textarea/textarea.vue
> feat(textarea): 新增input事件

- packages/nutui/components/input/input.vue
- packages/nutui/components/textarea/textarea.ts
- packages/nutui/components/textarea/textarea.vue
- `nut-input` `nut-textarea` 修复input事件返回值错误
- `nut-textarea` autosize类型错误
> fix(input,textarea): 修复input事件返回值错误

- docs/components/dentry/datepicker.md
- example/src/pages/demo/dentry/datepicker/index.vue
补充`datepicker`文档中`three-dimensional`
增加选择年月，与nutui对齐
将文字说明中的属性类型加上反引号
> docs(datepicker) 补充datepicker文档

- docs/components/dentry/input.md
- docs/components/dentry/textarea.md
- packages/nutui/components/input/input.ts
- packages/nutui/components/input/input.vue
- packages/nutui/components/textarea/textarea.ts
- packages/nutui/components/textarea/textarea.vue
`nut-input` 新增input-class、input-style属性
`nut-textarea` 新增textarea-class、textarea-style属性
> fix(input,textarea): 新增输入框单独控制样式属性

- packages/nutui/components/uploader/uploader.vue
> fix(uploader): 修复禁用时能删除文件的问题

- docs/components/business/addresslist.md
- example/src/pages/demo/business/addresslist/index.vue
- packages/nutui/components/addresslist/addresslist.ts
- packages/nutui/components/addresslist/addresslist.vue
- packages/nutui/components/addresslist/compoents/Itemcontents.vue
- packages/nutui/components/addresslist/compoents/generalshell.vue
- packages/nutui/components/addresslist/index.scss
`nut-addresslist` 新增是否使用插槽相关属性
> feat(addresslist): 新增是否使用插槽相关属性

- docs/components/business/addresslist.md
- example/src/pages/demo/business/addresslist/index.vue
- packages/nutui/components/addresslist/addresslist.ts
- packages/nutui/components/addresslist/addresslist.vue
- packages/nutui/components/addresslist/index.ts
- packages/nutui/components/addresslist/type.ts
> refactor(addresslist): 变更slot判断方式

- docs/components/dentry/input.md
- packages/nutui/components/input/input.vue
- packages/nutui/components/input/type.ts
`nut-input` 修复H5环境下type为number无效
> fix(input): 修复H5环境下type为number无效

- docs/components/dentry/searchbar.md
- example/src/pages/demo/dentry/searchbar/index.vue
- packages/nutui/components/input/input.vue
- packages/nutui/components/searchbar/index.scss
- packages/nutui/components/searchbar/index.ts
- packages/nutui/components/searchbar/searchbar.ts
- packages/nutui/components/searchbar/searchbar.vue
- packages/nutui/components/searchbar/type.ts
- packages/nutui/components/textarea/textarea.vue
- packages/nutui/styles/variables.scss
> fix(searchbar): 修复app端输入框对齐问题

- docs/components/feedback/swipe.md
- example/src/pages/demo/feedback/swipe/index.vue
- packages/nutui/components/swipe/index.scss
- packages/nutui/components/swipe/index.ts
- packages/nutui/components/swipe/swipe.ts
- packages/nutui/components/swipe/swipe.vue
- packages/nutui/components/swipe/type.ts
- packages/nutui/components/swipegroup/index.ts
- packages/nutui/components/swipegroup/swipegroup.vue
`nut-swipe` 修复组件宽度超出范围以及点击关闭问题
> fix(swipe): 修复组件宽度超出范围以及点击关闭问题

- docs/components/dentry/input.md
- example/src/pages/demo/dentry/input/index.vue
- packages/nutui/components/formitem/index.scss
- packages/nutui/components/input/index.scss
- packages/nutui/components/input/input.ts
- packages/nutui/components/input/input.vue
- packages/nutui/styles/variables.scss
> refactor(input)!: 重构input的dom结构

- docs/components/nav/menu.md
- packages/nutui/components/menuitem/menuitem.ts
- packages/nutui/components/menuitem/menuitem.vue
`nut-menu-item` 新增 `item-click` 事件
> feat(menuitem): 新增item-click事件

- docs/components/nav/tabs.md
- packages/nutui/components/tabpane/index.scss
- packages/nutui/styles/variables.scss
`nut-tab-pane` 新增padding、background样式变量
> feat(tab-pane): 新增padding、background样式变量

- docs/components/dentry/form.md
- example/src/pages/demo/dentry/form/index.vue
- packages/nutui/components/formitem/formitem.vue
- packages/nutui/components/formitem/type.ts
`nut-form` 自定义validator支持返回Error
> feat(form): 自定义validator支持返回Error

- packages/nutui/components/formitem/formitem.vue
- packages/nutui/components/formitem/index.scss
- packages/nutui/components/formitem/type.ts
> feat(form): 新增校验状态

- packages/nutui/components/toast/toast.vue
`nut-toast` 修复部分情况下toast的duration属性无效
> fix(toast): 修复部分情况下toast的duration属性无效

- docs/components/basic/transition.md
- docs/components/dentry/cascader.md
> docs: 完善Cascader文档示例

- example/src/pages/demo/business/comment/index.vue
- packages/nutui/components/comment/comment.vue
> fix: 修复comment生产环境web端卡死

- docs/components/exhibition/swiper.md
> docs: 完善Swiper文档示例

- docs/components/nav/menu.md
- example/src/layouts/default.vue
- example/src/pages/demo/nav/menu/index.vue
- example/src/pages/index/index.vue
- packages/nutui/components/menu/menu.ts
- packages/nutui/components/menu/menu.vue
> feat(menu): add scroll-top prop

- packages/nutui/components/avatar/avatar.vue
> fix(avatar): 修复支付宝小程序不支持??语法

- docs/components/basic/cell.md
- example/src/pages/demo/basic/cell/index.vue
- packages/nutui/components/cell/cell.ts
- packages/nutui/components/cell/cell.vue
- packages/nutui/components/cell/index.scss
- packages/nutui/components/cell/index.ts
- packages/nutui/components/cellgroup/cellgroup.ts
- packages/nutui/components/cellgroup/cellgroup.vue
- packages/nutui/components/cellgroup/index.scss
- packages/nutui/components/cellgroup/index.ts
> feat(cell): 新增icon、clickable属性

- docs/components/dentry/checkbox.md
- example/src/pages/demo/dentry/checkbox/index.vue
- packages/nutui/components/checkbox/checkbox.ts
- packages/nutui/components/checkbox/checkbox.vue
- packages/nutui/components/checkbox/index.scss
- packages/nutui/components/checkboxgroup/checkboxgroup.ts
- packages/nutui/components/checkboxgroup/checkboxgroup.vue
- packages/nutui/components/checkboxgroup/index.ts
- packages/nutui/components/checkboxgroup/types.ts
- packages/nutui/components/form/form.ts
- packages/nutui/components/input/input.ts
- packages/nutui/components/inputnumber/inputnumber.ts
- packages/nutui/components/radio/radio.ts
- packages/nutui/components/range/range.ts
- packages/nutui/components/rate/rate.ts
- packages/nutui/components/searchbar/searchbar.ts
- packages/nutui/components/textarea/textarea.ts
- packages/nutui/components/uploader/uploader.ts
> feat(checkbox): 新增checked-value、unchecked-value属性

- .stylelintrc
> chore: update stylelint shorthands rule

- packages/nutui/components/shortpassword/index.scss
> 适配2021年前的旧机型

- packages/nutui/components/inputnumber/index.scss
> chore(input-number): fix scss warning

- packages/nutui/components/popover/index.scss
- packages/nutui/components/shakedice/index.scss
- packages/nutui/components/tour/index.scss
[Breaking Change: Mixed Declarations](https://sass-lang.com/documentation/breaking-changes/mixed-decls)
#370 #371 #409 #413
> fix(popover,shakedice,tour): fix scss warning

- docs/components/basic/cell.md
- packages/nutui/components/cell/cell.ts
- packages/nutui/components/cell/cell.vue
- packages/nutui/components/cellgroup/cellgroup.vue
> feat(cell): 新增title-width属性

- docs/components/dentry/inputnumber.md
- example/src/pages/demo/dentry/inputnumber/index.vue
- packages/nutui/components/inputnumber/inputnumber.ts
- packages/nutui/components/inputnumber/inputnumber.vue
> fix(inputnumber): 修复失焦后未正确按照最大/最小值修改输入值

- docs/components/basic/popup.md
- docs/components/dentry/calendar.md
- docs/components/dentry/cascader.md
- packages/nutui/components/calendar/calendar.ts
- packages/nutui/components/calendar/calendar.vue
- packages/nutui/components/calendar/index.scss
- packages/nutui/components/calendar/index.ts
- packages/nutui/components/calendaritem/calendaritem.ts
- packages/nutui/components/calendaritem/calendaritem.vue
- packages/nutui/components/calendaritem/index.scss
- packages/nutui/components/calendaritem/types.ts
- packages/nutui/components/cascader/cascader.ts
- packages/nutui/components/cascader/cascader.vue
- packages/nutui/components/cascader/helper.ts
- packages/nutui/components/cascader/index.scss
- packages/nutui/components/cascader/index.ts
- packages/nutui/components/cascader/types.ts
- packages/nutui/components/cascaderitem/cascaderitem.ts
- packages/nutui/components/cascaderitem/cascaderitem.vue
- packages/nutui/components/cascaderitem/index.scss
- packages/nutui/components/cascaderitem/index.ts
- packages/nutui/components/popup/index.scss
- packages/nutui/components/popup/popup.ts
- packages/nutui/components/popup/popup.vue
> feat(calendar,cascader)!: 新增open/opened、close/closed事件（重构DOM结构）

- docs/components/feedback/dialog.md
- packages/nutui/components/dialog/use-dialog.ts
> fix(dialog): 修复小程序平台启用`close-on-popstate`时onMounted报错

- packages/nutui/components/shortpassword/shortpassword.vue
> fix(short-password): 修复 `close-on-click-overlay` 属性无效

- packages/nutui/components/popup/use-popup.ts
> fix(popup): 修复 `visible` 初始值为 `true` 时丢失 `z-index` 问题

- packages/nutui/components/uploader/uploader.vue
> fix(uploader): 修复uploader组件在app端，succes事件之后还执行progress事件的问题

- packages/nutui/components/menu/menu.vue
- packages/nutui/components/menuitem/menuitem.vue
`menu`组件在app平台会报错，导致`menu-item`渲染错误
`
Maximum recursive updates exceeded in component <nut-menu>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.
`
将`renderTitle`改为`computed`后可解决
> fix(menu): 修复menu组件在app平台报错的问题

- packages/nutui/components/input/input.ts
> fix: nut-input 默认光标在末尾

- docs/.vitepress/items.ts
> docs: 修正Overlay组件文本为“遮罩层” #463

- docs/components/business/category.md
> docs(category): 修改示例代码错误

- packages/nutui/components/cascader/index.scss
> fix(cascader): 修复级联选择器选中和不可选的样式层级错误

- packages/nutui/components/category/category.ts
- packages/nutui/components/category/category.vue
- packages/nutui/components/category/index.scss
- packages/nutui/components/categorypane/categorypane.ts
- packages/nutui/components/categorypane/categorypane.vue
> fix(category): 修改div标签

- docs/components/business/card.md
> docs(card): 移除无效 event 说明
