packages/nutui/components/dialog/dialog.vue
在使用ref方式调用对话框时，取消按钮无法通过noCancelBtn属性隐藏，条件渲染现已修改为：`v-if="!dialogStatus.noCancelBtn"`
=> fix: 修复通过ref调用对话框时，noCancelBtn属性无效的bug

packages/nutui/components/input/index.scss
Fixes https://github.com/yang1206/uniapp-nutui/issues/21
=> fix: (input) 修复左右插件默认文字无法显示

packages/nutui/components/input/input.vue
input组件的type值：digit与number的值校验逻辑似乎是反了，在微信小程序中，number类型弹出的数字输入法不带小数点，但值校验允许输入小数点，而ditit类型的数字输入法带小数点，值却不允许输入小数点，两者的值校验逻辑在原代码中似乎反了，现已更正并在项目中被验证，若此问题无需更改请将这个pr关闭。☺️
=> fix(input): 修复type值number与digit两个校验逻辑反了

packages/nutui/components/picker/picker.vue
在非h5环境下使用picker组件，会导致无法真机调试
小程序在使用picker组件后，就会出现此问题
=> fix: (picker)修复在非h5环境下多余引入导致无法真机调试

docs/components/basic/configprovider.md
docs: 暗黑模式下颜色css变量名称错误--nut-nut-
=> docs: 暗黑模式下颜色css变量名称错误--nut-nut-

.stylelintrc, packages/nutui/styles/reset.css
当前在小程序环境下，添加了 `cursor: pointer;` 样式的组件在点击时会有默认的高亮样式，这与 H5 模式下表现不一致。例如：设置了 `is-link` 的 `Cell` 组件。
=> fix(style): highlight

packages/nutui/components/badge/badge.vue
=> fix(badge): badge的top、right不支持rpx单位

docs/components/basic/overlay.md, docs/components/basic/popup.md, docs/components/business/timeselect.md, docs/components/feedback/dialog.md, docs/components/nav/menu.md, packages/nutui/components/overlay/overlay.vue, packages/nutui/components/popup/popup.vue
小程序移除`lock-scroll`属性支持
BREAKING CHANGE: 小程序移除`lock-scroll`属性支持
所有依赖overlay的组件的`lock-scroll`属性同理也将不再支持小程序与 APP 平台,禁用滚动穿透方法可参考文档
closed #103
=> fix(overlay)!: 小程序与 APP平台不再支持`lock-scroll`属性

packages/nutui/components/_utils/props.ts, packages/nutui/components/formitem/formitem.ts, packages/nutui/components/formitem/formitem.vue
当前逻辑无法实现必填校验字段不显示星号，应该尊重用户不显示星号的配置。
=> fix(formitem): 提高传入 required 的优先级

packages/nutui/components/popup/popup.vue, packages/nutui/components/popup/use-popup.ts, packages/nutui/components/textarea/index.scss, packages/nutui/components/textarea/textarea.vue, packages/nutui/components/transition/index.scss, packages/nutui/components/transition/transition.vue, packages/nutui/components/transition/use-transition.ts
1、textarea启用autosize时readonly与普通状态下的样式不统一；
2、app端v-show使用display:none控制隐藏的样式优先级不足，导致transition组件无法关闭。 #142
=> fix(textarea): 启用autosize时readonly样式不统一；fix(transition): 组件无法正常关闭；

packages/nutui/components/calendar/calendar.vue, packages/nutui/components/calendaritem/calendaritem.vue
1. 日历组件在微信小程序弹窗未打开时，修改scrollTop无法触发@scroll事件，导致打开弹窗后页面空白且无法滚动到默认日期 #152
2. 日历组件在微信小程序中无法显示今天标记 #153
=> fix(calendar): 日历组件在微信小程序弹窗展示时，无法滚动到默认日期；fix(calendar): 日历组件在微信小程序中无法显示今天标记

packages/nutui/components/navbar/navbar.vue
navBarHtml节点的css样式里面已经包含了状态栏高度,占位元素高度不需要再重复计算一次
=> fix(navbar): 修复占位元素重复计算状态栏高度的问题

packages/nutui/components/input/input.vue
=> fix(input): 修复readonly无效

docs/components/basic/popup.md, packages/nutui/components/transition/transition.vue
`nut-transition`及衍生组件在app端destroyOnClose属性无效
=> fix(transition): app端destroyOnClose属性无效

packages/nutui/components/textarea/textarea.ts, packages/nutui/components/textarea/type.ts
`nut-textarea` 修复ConfirmType导出类型名称重复以及默认值错误
=> fix(textarea): 修复ConfirmType导出类型名称重复以及默认值错误

packages/nutui/components/input/input.ts, packages/nutui/components/input/type.ts
=> refactor(input): 统一input类型命名规则

packages/nutui/components/uploader/uploader.ts, packages/nutui/components/uploader/uploader.vue
`nut-uploader` 修复beforeDelete默认值无效以及不支持promise
=> fix(uploader): 修复beforeDelete默认值无效以及不支持promise

docs/components/dentry/uploader.md, example/src/pages/demo/dentry/uploader/index.vue, packages/nutui/components/uploader/uploader.vue, packages/nutui/components/uploader/use-uploader.ts
=> feat(uploader):  新增accept配置

packages/nutui/components/picker/index.scss, packages/nutui/components/picker/picker.vue
微信小程序`picker-view`有默认的蒙层样式,通过`mask-class`去除默认蒙层样式
#235
=> fix(picker): 修复微信小程序暗黑模式picker背景颜色显示错误的问题

packages/nutui/components/input/input.vue
ui版本：1.7.10
机型：小米mix4（hyper os 1.0.2.0.UKMCNXM）Android14
微信版本：8.0.49
在微信开发者工具上结果是正确的。
在手机上点击清除图标，实测先触发clear，再触发blur，再触发update:modelValue，这时会把blur中得到的值传给update:modelValue，导致需要点很多次才能清除
解决方式：捕获blur，优先触发blur再触发clear
=> 修复 在Android14微信小程序中，input focus后点击清除，值实际未清除的问题

packages/nutui/components/input/input.vue
使用innerValue.value的值代替blur事件返回的值
关联：https://github.com/nutui-uniapp/nutui-uniapp/issues/309
=> 使用innerValue.value的值代替blur事件返回的值

packages/nutui/components/navbar/index.scss
1、微信小程序只支持 env，参考 https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/wxss.html#%E7%B1%BB%E5%9E%8B%E6%94%AF%E6%8C%81%E5%88%97%E8%A1%A8。
2、--status-bar-height 在小程序固定为 25px，在 IOS 下使用 navbar safe-area-inset-top  时无法填满整个状态栏： iPhone X/XR/XS Max 状态栏高度为 44px，12/13 mini/pro/pro max 状态栏高度为 47px，14/15 pro max状态栏高度为54px。故注释此样式。 参考 https://uniapp.dcloud.net.cn/tutorial/syntax-css.html#css-%E5%8F%98%E9%87%8F。
=> fix(navbar): 修复 navbar safe-area-inset-top 不生效的问题

packages/nutui/components/numberkeyboard/index.scss
部分机型对 Inset 不支持，当 number-key-board 在带有右侧删除按钮和完成按钮时无法铺满，此次修改主要是提升兼容性。
=> 适配2021年前的旧机型

docs/components/dentry/searchbar.md, packages/nutui/components/searchbar/searchbar.ts, packages/nutui/components/searchbar/searchbar.vue
移除clickLeftIcon与clickRightIcon事件,因为可以使用 slot 替代事件,这避免了一些 api 混乱
link #416
=> refactor!: 移除clickLeftIcon与clickRightIcon事件

packages/nutui/components/picker/index.scss
`picker`组件最外层未指定宽度，如果`picker`被`flex`元素包裹，并且`showToolbar`为`false`时，宽度为0
=> fix(picker): 修复showToolbar等于false时,picker组件宽度为0不显示的问题

packages/nutui/components/_hooks/useSelectorQuery.ts
app平台createSelectorQuery不需要in参数，传入后会获取不到节点数据
=> fix(hooks): 修复useSelectorQuery在app平台查询节点数据为空的问题

packages/nutui/components/menu/index.scss, packages/nutui/components/menuitem/index.scss, packages/nutui/components/menuitem/menuitem.vue
修复了 Menu 组件在切换和关闭菜单时的交互问题。主要解决了以下几个问题：
1. 修复向下展开的菜单需要点击两次才能切换的问题
- 原因：遮罩层的 z-index 高于菜单项，导致第一次点击实际点击到了遮罩层
- 解决：调整了遮罩层的 z-index 优先级，确保菜单项可以正常响应点击事件
2. 修复向上展开的菜单点击空白处无法关闭的问题
- 原因：遮罩层定位不正确，未能完全覆盖需要响应点击的区域
- 解决：修正了遮罩层的定位逻辑
3. 优化了菜单展开时的样式表现
这些修改确保了菜单可以在一次点击时正常切换，同时保持了点击空白处关闭菜单的功能。
fix [#448](https://github.com/nutui-uniapp/nutui-uniapp/issues/448)
该修复改进了 Menu 组件的用户体验，使其行为更符合用户预期：
- 菜单切换时更加流畅，无需多次点击
- 保持了点击空白处关闭菜单的功能
- 统一了向上和向下展开菜单的交互体验
=> fix(menu): 修复点击菜单无法正常切换的问题

docs/components/dentry/input.md, packages/nutui/components/input/input.ts, packages/nutui/components/input/input.vue
我试了下项目里用 `useAttrs` 是可以的，但用 `v-bind` 编译时报错说不支持，那只能加单个属性了，想真机预览时报错说不是开发者，微信小程序这限制是真难受
Fix #455
=> feat(input): 新增 password 属性

packages/nutui/components/transition/index.ts, packages/nutui/components/transition/transition.ts, packages/nutui/components/transition/transition.vue, packages/nutui/components/transition/types.ts, packages/nutui/components/transition/use-transition.ts
部分环境中，混合连续使用 `?.` 和 `?:` 导致编译报错 `TypeError: "a" is read-only`
```ts
animationClass.value = defaultAnimations[name.value]?.enter
? defaultAnimations[name.value]?.enter
: `${classNames.value.enter} ${classNames.value.enterActive}`
```
link #461
=> fix(transition): 修复部分环境编译报错

docs/components/business/sku.md, packages/nutui/components/sku/sku.vue, packages/nutui/components/textarea/index.scss
解决sku在不使用头部skuHeaderPrice和skuHeaderExtra插槽时也会被判断为使用，导致头部插槽右侧不显示的问题
Fix #468
=> fix(sku): 修复header内插槽的显示判断

packages/nutui/components/tabs/tabs.vue
修复自定义标签栏找不到元素的报错
其实我觉得这个自定义标签栏的颗粒度不对，如果只是想修改的item内部显示（很常见的需求），那设置的title-scroll属性就直接失效了，滚动效果和动效就直接没了
=> fix(tabs): 修复自定义标签栏找不到元素的报错
